[package]
name = "ninjoonline/Cmdr"
description = "Extensible command console for Roblox developers"
version = "1.9.3"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
