[package]
name = "ninjoonline/cmdr"
description = "Extensible command console for Roblox developers"
version = "1.9.2"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
